### ISSUE TITLE
I think you could use this main to initialise Client, it already runs by default in a thread

### ISSUE THREAD

**Issue by giselacostamindera** [rodgreg02/TUIClient#9]
https://github.com/rodgreg02/TUIClient/blob/b7852b7c17a8a6dc6cfcae9bf709aebdd055d571/src/main/java/org/example/Main.java#L6

**Comment by giselacostamindera** [comment]
Also Client and TerminalUserInterface, I believe do not need to extend thread.

**Comment by rodgreg02** [comment]
Fixed, removed class Client, deprecated, removed extend Thread in TerminalUserInterface and moved init to Main
